# Generated by Django 4.2.11 on 2024-03-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0004_place_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('date_time_of_publication', models.DateTimeField(auto_now_add=True)),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.place')),
            ],
            options={
                'ordering': ['-date_time_of_publication'],
            },
        ),
    ]
