# Generated by Django 4.2.11 on 2024-03-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_place_user'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.place')),
            ],
        ),
    ]
