# Generated by Django 4.2.11 on 2024-03-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_place_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
    ]
