# Generated by Django 4.2.11 on 2024-03-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_remove_review_place_remove_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Mountain', 'Mountain'), ('Sea', 'Sea'), ('Historical Site', 'Historical Site'), ('City', 'City'), ('Spa', 'Spa'), ('Wine Tourism', 'Wine Tourism')]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
