# Generated by Django 4.2.11 on 2024-03-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.IntegerField(blank=True, choices=[('1 Star', '1 Star'), ('2 Stars', '2 Stars'), ('3 Stars', '3 Stars'), ('4 Stars', '4 Stars'), ('5 Stars', '5 Stars')], null=True),
        ),
    ]
