# Generated by Django 4.2.11 on 2024-03-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_alter_place_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, choices=[('Mountain', 'Mountain'), ('Sea', 'Sea'), ('Historical Site', 'Historical Site'), ('City', 'City'), ('Spa', 'Spa'), ('Wine Tourism', 'Wine Tourism')], max_length=100, null=True),
        ),
    ]
