# Generated by Django 4.2.11 on 2024-03-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_alter_place_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Photo'),
        ),
    ]
