# Generated by Django 4.2.11 on 2024-03-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0008_place_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='photo',
        ),
    ]
