# Generated by Django 4.2.11 on 2024-03-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0009_remove_place_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.ImageField(default='https://...', error_messages={'unique': 'This image URL is already in use! Provide a new one.'}, unique=True, upload_to='', verbose_name='Image URL'),
        ),
    ]
