# Generated by Django 4.2.11 on 2024-03-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0010_alter_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
