# Generated by Django 4.2.11 on 2024-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0012_alter_place_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='hotel_name',
        ),
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/photos'),
        ),
    ]
