# Generated by Django 4.2.11 on 2024-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0013_rename_name_place_hotel_name_alter_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='hotel_name',
            field=models.CharField(max_length=200, verbose_name='Hotel name'),
        ),
    ]
