# Generated by Django 4.2.11 on 2024-04-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0014_alter_place_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_url',
        ),
        migrations.AddField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/photos', verbose_name='Hotel photo'),
        ),
    ]
