# Generated by Django 4.2.11 on 2024-04-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0016_alter_place_category_alter_place_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='photo',
            new_name='image_url',
        ),
    ]
