# Generated by Django 4.2.11 on 2024-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0017_rename_photo_place_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/videos'),
        ),
    ]
