# Generated by Django 4.2.11 on 2024-03-08 04:05

from django.db import migrations, models
import my_holiday.accounts.valodators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, validators=[my_holiday.accounts.valodators.validator_username, my_holiday.accounts.valodators.validate_username_length], verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('profile_photo', models.URLField(blank=True, null=True, verbose_name='Profile Photo')),
            ],
        ),
    ]
