# Generated by Django 4.2.11 on 2024-03-17 12:56

from django.db import migrations, models
import my_holiday.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myholidayuser_groups_myholidayuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myholidayuser',
            managers=[
                ('objects', my_holiday.accounts.managers.MyHolidayUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='myholidayuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myholidayuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
