# Generated by Django 4.2.11 on 2024-04-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/photos', verbose_name='Profile Photo'),
        ),
    ]
